#!/usr/bin/env bash
set -euo pipefail

# Generate weekly distill review
# Usage: ./weekly-review.sh

OUTPUT_DIR="${HOME}/clawd/distill"
MEMORY_DIR="${HOME}/clawd/memory"
PROGRESS_DIR="${HOME}/clawd/progress"

mkdir -p "$OUTPUT_DIR"

DATE=$(date '+%Y-%m-%d')
WEEK_START=$(date -d "last sunday" '+%Y-%m-%d' 2>/dev/null || date -v -sun '+%Y-%m-%d' 2>/dev/null || echo "$DATE")
OUTPUT_FILE="$OUTPUT_DIR/${DATE}-weekly.md"

echo "# Weekly Distill Review - Week of $WEEK_START" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Generated: $(date '+%Y-%m-%d %H:%M')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Count recent files
MEMORY_COUNT=$(find "$MEMORY_DIR" -type f -name "*.md" -mtime -7 2>/dev/null | wc -l || echo "0")
PROGRESS_COUNT=$(find "$PROGRESS_DIR" -type f \( -name "*.md" -o -name "*.txt" \) -mtime -7 2>/dev/null | wc -l || echo "0")

echo "## This Week's Activity" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "- Memory files updated (last 7 days): $MEMORY_COUNT" >> "$OUTPUT_FILE"
echo "- Progress files updated (last 7 days): $PROGRESS_COUNT" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# List recent files
echo "## Recent Files" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [[ -d "$MEMORY_DIR" ]]; then
    echo "### Memory" >> "$OUTPUT_FILE"
    find "$MEMORY_DIR" -type f -name "*.md" -mtime -7 -exec basename {} \; 2>/dev/null | head -10 | while read -r f; do
        echo "- $f" >> "$OUTPUT_FILE"
    done
    echo "" >> "$OUTPUT_FILE"
fi

if [[ -d "$PROGRESS_DIR" ]]; then
    echo "### Progress" >> "$OUTPUT_FILE"
    find "$PROGRESS_DIR" -type f \( -name "*.md" -o -name "*.txt" \) -mtime -7 -exec basename {} \; 2>/dev/null | head -10 | while read -r f; do
        echo "- $f" >> "$OUTPUT_FILE"
    done
    echo "" >> "$OUTPUT_FILE"
fi

# Extract action items
echo "## Open Action Items" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Search for unchecked items
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -x "$SCRIPT_DIR/extract-actions.sh" ]]; then
    "$SCRIPT_DIR/extract-actions.sh" "$HOME/clawd" 2>/dev/null | grep -E "^- " | head -20 >> "$OUTPUT_FILE" || echo "- No action items found" >> "$OUTPUT_FILE"
else
    # Inline action extraction
    grep -rn "\\[ \\]\\|TODO\\|FIXME" "$HOME/clawd" 2>/dev/null | head -15 | while read -r line; do
        echo "- $line" >> "$OUTPUT_FILE"
    done
fi
echo "" >> "$OUTPUT_FILE"

# Evolution Queue status
echo "## Evolution Queue Status" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
QUEUE_FILE="$HOME/clawd/EVOLUTION-QUEUE.md"
if [[ -f "$QUEUE_FILE" ]]; then
    PENDING=$(grep -c "Status:.*pending" "$QUEUE_FILE" 2>/dev/null || echo "0")
    RESOLVED=$(grep -c "RESOLVED" "$QUEUE_FILE" 2>/dev/null || echo "0")
    echo "- Pending items: $PENDING" >> "$OUTPUT_FILE"
    echo "- Resolved this week: $RESOLVED" >> "$OUTPUT_FILE"
else
    echo "- Evolution Queue not found" >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Generated by distill skill*" >> "$OUTPUT_FILE"

echo "Weekly review generated: $OUTPUT_FILE"
